services:
    app:
        container_name: app
        build:
            context: .
            dockerfile: .docker/Dockerfile
#            dockerfile: .docker/Dockerfile-xdebug
        environment:
            APP_ENV: "dev"
            DATABASE_URL: "mysql://root:mysql@mysql/sylius_%kernel.environment%?charset=utf8mb4"
#            DATABASE_URL: "pgsql://root:postgres@postgres/sylius_%kernel.environment%?charset=utf8" # When using postgres
            PHP_DATE_TIMEZONE: "Europe/Warsaw"
            PHP_IDE_CONFIG: serverName=PHPSTORM
        volumes:
            - ./:/app:delegated
            - ./.docker/php.ini:/etc/php8/php.ini:delegated
            - ./.docker/nginx.conf:/etc/nginx/nginx.conf:delegated
        ports:
            - 80:80
        depends_on:
            - mysql
        networks:
            - sylius

    mysql:
        container_name: mysql
        image: mysql:8.0
        platform: linux/amd64
        volumes:
            - mysql-data:/var/lib/mysql:rw
        environment:
            MYSQL_ROOT_PASSWORD: mysql
        ports:
            - ${MYSQL_PORT:-3306}:3306
        networks:
            - sylius

#    postgres:
#        image: postgres:14-alpine
#        environment:
#            POSTGRES_USER: root
#            POSTGRES_PASSWORD: postgres
#        ports:
#            - ${POSTGRES_PORT:-5432}:5432
#        networks:
#            - sylius

networks:
    sylius:
        driver: bridge

volumes:
    mysql-data:
