sylius_twig_hooks:
  hooks:
    'sylius_shop.product.show.content.info.summary.add_to_cart':
     bundle:
       component: 'sylius_shop:product:add_to_cart_form'
       props:
         product: '@=_context.product'
         template: '@BitBagSyliusProductBundlePlugin/Shop/product/show/page/info/summary/add_to_cart/addProductBundleToCart.html.twig'
       priority: 20
