imports:
    - { resource: resources.yml }
    - { resource: services.xml }

framework:
    messenger:
        buses:
            bitbag_sylius_product_bundle.command_bus: ~
    mailer:
        dsn: '%env(MAILER_DSN)%'