imports:
    - { resource: resources.yml }
    - { resource: services.xml }
    - { resource: "@BitBagSyliusProductBundlePlugin/Resources/config/twig_hooks/twig_hooks.yaml" }

framework:
    messenger:
        buses:
            bitbag_sylius_product_bundle.command_bus: ~
