sylius_twig_hooks:
  hooks:
    'sylius_admin.order.show.content.sections.items.body':
      item:
        template: '@SyliusAdmin/order/show/content/sections/items/body/item.html.twig'
        priority: 800
