sylius_resource:
    resources:
        bitbag_sylius_product_bundle.product_bundle_order_item:
            driver: doctrine/orm
            classes:
                model: BitBag\SyliusProductBundlePlugin\Entity\ProductBundleOrderItem
                interface: BitBag\SyliusProductBundlePlugin\Entity\ProductBundleOrderItemInterface
