sylius_twig_hooks:
  hooks:
    'sylius_admin.product.create.content.form.side_navigation':
      channel_pricing:
      bundle:
        template: '@BitBagSyliusProductBundlePlugin/Admin/product/form/side_navigation/bundle.html.twig'

    'sylius_admin.product.create.content.form.sections':
      bundle:
        template: '@BitBagSyliusProductBundlePlugin/Admin/product/form/sections/bundle.html.twig'

    'sylius_admin.product.create.content.form.sections.bundle':
      product_bundle:
        template: '@BitBagSyliusProductBundlePlugin/Admin/product/form/sections/bundle/productBundleItem.html.twig'
